# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: LabLib-pytest-ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        - name: Add conda to system path
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Install OpenImageIO
      run: |
        conda install -c conda-forge openimageio py-openimageio
    - name: Test with pytest
      run: |
        poetry run pytest
